# Generated by Django 3.0.7 on 2020-09-02 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sw_currency', '0001_initial'),
        ('sw_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAdditionalPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Ціна')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='sw_order.OrderConfig', verbose_name='Налаштування')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sw_currency.Currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'емейл для сповіщень про замовлення',
                'verbose_name_plural': 'емейли для сповіщень про замовлення',
            },
        ),
    ]
